### PR TITLE
Update to use CircleCI

### PR DESCRIPTION
**Pull request by robhudson**
CircleCI is the preferred platform for building docker images and pushing the to docker hub. This switches our testing from TravisCI to CircleCI.

### CODE REVIEW

**Comment by robhudson** [comment]
@openjck This says all checks have passed but the gulp jest stuff failed. Mind taking a quick look when you have a moment? Next week I can try to debug more also but any insights would be helpful.

**Comment by openjck** [comment]
That's so interesting. I can't imagine why the tests are failing, but I'll keep digging into it.

More importantly, I don't understand why the test failure didn't break the build. When tests fail locally, they return with error code 1.

**Comment by openjck** [comment]
Fixed. Looks like we just needed to add _babel-jest_ to _package.json_. Not sure why we didn't need it locally or on Travis.

**Comment by robhudson** [comment]
Cool, thanks @openjck ! 👻

**Pull request merged**
