### PR TITLE
Add HSTS headers on static assets

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by robhudson** [comment]
r? @psiinon  (wrt bug 1371580)

Apologies for the delay.

**Comment by robhudson** [comment]
On further thought, I should combine this with #283 and #293 and resubmit. I didn't realize these were all there.

**Comment by psiinon** [comment]
@robhudson wfm :)

**Comment by robhudson** [comment]
Updated

**Review by psiinon — APPROVED** [review]
Looks good, as far as I can tell ;)

**Comment by robhudson** [comment]
Thanks. I'll merge/push and we can re-run the checker once it's deployed.

**Pull request merged**
