### PR TITLE
Remove CORS header and set anti-mime-sniffing header

### PR DESCRIPTION
**Pull request by psiinon**
As per https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cross-origin_Resource_Sharing and https://wiki.mozilla.org/Security/Guidelines/Web_Security#X-Content-Type-Options

### CODE REVIEW

**Comment by openjck** [comment]
Rob is out this week. Do you have time to take a look, @washort?

**Comment by washort** [comment]
Looks good but to fix CORS headers on static files, you'll need to add `WHITENOISE_ALLOW_ALL_ORIGINS = False`

**Comment by robhudson** [comment]
Closing in favor of #329

**Pull request closed without merging**
