### PR TITLE
Rename metric.metric to metric.name in API output

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by robhudson** [comment]
Mind force pushing this again? The tests didn't run.

**Comment by robhudson** [comment]
r+ assuming tests pass.

**Comment by openjck** [comment]
Just re-pushed twice but tests still aren't starting. Hmm...

**Review by robhudson — CHANGES_REQUESTED** [review]
You'll need to update the expected dictionary in `distributionviewer/api/tests/test_views.py` for the "test_basic" test.

**Comment by openjck** [comment]
> You'll need to update the expected dictionary in distributionviewer/api/tests/test_views.py for the "test_basic" test.

Ah, good catch. Forgot to update tests. I'll do that.

**Comment by openjck** [comment]
Updated

**Review by robhudson — APPROVED** [review]

**Pull request merged**
