### PR TITLE
Add concept of datasets for historical data (fixes #62)

### LINKED ISSUE #62: Add ability for multiple distributions based on date range
My idea for a data model for this is the following:

An extra `distributions` table with `date_start` and `date_end` columns. Then the category collection and log collection would contain a field for the `distribution_id` that is a foreign key to the distribution.

Any queries to the API would provide a date that would look up the distribution record to then query the collection tables.

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by openjck** [comment]
Nice! Just one quick thing while I try it out: we might also want to update _api.md_ to document the new `dataSet` property.

**Comment by openjck** [comment]
Hmm... I'm getting an error when I try to migrate locally. Is there additional sample data that needs to be loaded to use this feature?

```
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, contenttypes, api, auth, sessions
Running migrations:
  Applying api.0004_auto_20160906_2304...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "api_categorycollection" violates foreign key constraint "api_categorycollection_dataset_id_ef3ff939_fk_api_dataset_id"
DETAIL:  Key (dataset_id)=(1) is not present in table "api_dataset".
```

**Comment by robhudson** [comment]
I flattened the migrations. What this requires after merge locally is:

```
$ dropdb distributionviewer
$ createdb -Odistributionviewer -Eutf8 distributionviewer
$ ./manage.py migrate
```

Now you will have no data. To load fake data it is similar to before but you now have the option to import multiple datasets. Via `./manage.py shell` do the following for 2 datasets...

```
>>> import datetime
>>> from distributionviewer.api.fakedata import load
>>> load(datetime.date(2016, 8, 28))  # first dataset.
>>> load(datetime.date(2016, 9, 4))  # second dataset.
```

Note: I can put some of this in the commit comment when merging so it's documented how to reset the database with this commit.

**Comment by openjck** [comment]
Looks good to me. If anything, one small piece of confusion for me was that `?date` requires _yyyymmdd_ whereas `dataSet` returns _yyyy-mm-dd_.

**Comment by robhudson** [comment]
@openjck Would it be preferred that the URL date format be `?date=2016-09-08` to match what's returned in the API? That makes sense to me.

**Comment by openjck** [comment]
Sure! That's the format I tried first, so that works for me.

**Comment by openjck** [comment]
And maybe this would be a good time to document `?date` and the format it accepts in _api.md_ too.

**Comment by robhudson** [comment]
@openjck Updated the data query param to accept ISO 8601 dates. Adjusted the docs to include this also.

**Comment by openjck** [comment]
Looks great! Thanks for the updates. r+

**Pull request merged**
