### PR TITLE
Fix #115, fix #112: Load charts with Redux

### LINKED ISSUE #112: Add `id` to individual metric endpoint
Because @spasovski said so.

### LINKED ISSUE #115: Load charts with Redux
We currently have an axios call directly in _chart.js_. We should move that to _metric-api.js_ so that chart loading can take advantage of Redux.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
This was a lot of work but I'm really happy with the result. We can now take advantage of Redux when loading charts. Code is also better organized with all API calls happening in _metrics-api.js_.

In the future, we could improve `getMetrics()` further to dispatch the array of metric data every time an element is added. That way, `ChartList` could load as soon as one chart is available and render more charts as they become available.

**Comment by robhudson** [comment]
I'm excited to look at this closely on Monday. Also 😢'ing at the rebase I'll do after this lands. But it's all good, 💯% ok with that.

**Comment by spasovski** [comment]
Great approach and works well locally! Thanks.

**Comment by openjck** [comment]
> I'm excited to look at this closely on Monday. Also 😢'ing at the rebase I'll do after this lands. But it's all good, 💯% ok with that.

I'd love to help. I'll ping you about it tomorrow.

**Pull request merged**
